const actions = {
  SIGN_IN_CHANGE_LOGIN: 'SIGN_IN_CHANGE_LOGIN',
  SIGN_IN_CHANGE_PASSWORD: 'SIGN_IN_CHANGE_PASSWORD',
  SIGN_IN_CHANGE_REMEMBER: "SIGN_IN_CHANGE_REMEMBER",
  SIGN_IN_IS_LOADING: "SIGN_IN_IS_LOADING",
  SIGN_IN_HAS_ERRORED: "SIGN_IN_HAS_ERRORED",
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  LOAD_USER: 'LOAD_USER',
  USER_IS_LOADING: 'USER_IS_LOADING',
  SET_USER_EMAIL: 'SET_USER_EMAIL',
  SET_IS_VALID_TOKEN: 'SET_IS_VALID_TOKEN',
  SET_NEW_PASSWORD: 'SET_NEW_PASSWORD',
  CONFIRM_NEW_PASSWORD: 'CONFIRM_NEW_PASSWORD',
  SET_EMAIL_ERROR: 'SET_EMAIL_ERROR',
  SET_PASSWORD_ERROR1: 'SET_PASSWORD_ERROR1',
  SET_PASSWORD_ERROR2: 'SET_PASSWORD_ERROR2',
  SET_NO_ERRORS: 'SET_NO_ERRORS',
  SET_EMAIL_MODAL: 'SET_EMAIL_MODAL',
  SET_EMAIL_NO_ERROR: 'SET_EMAIL_NO_ERROR',
  FORM_IS_LOADING: 'FORM_IS_LOADING'
}

export default actions;
