const actions = {
	DOCUMENT_CLEAN_STORE: "DOCUMENT_CLEAN_STORE",
	DOCUMENT_LOAD_FORM: "DOCUMENT_LOAD_FORM",
	DOCUMENT_LOAD_DEFAULT_VALUE: "DOCUMENT_LOAD_DEFAULT_VALUE",
	DOCUMENT_LOAD_PACKAGES: "DOCUMENT_LOAD_PACKAGES",
	DOCUMENT_CHANGE_WORKFLOW_TYPE_ID: "DOCUMENT_CHANGE_WORKFLOW_TYPE_ID",
	DOCUMENT_CHANGE_TITLE: "DOCUMENT_CHANGE_TITLE",
	DOCUMENT_CHANGE_TITLE_IMAGE_OPTION: "DOCUMENT_CHANGE_TITLE_IMAGE_OPTION",
	DOCUMENT_CHANGE_TITLE_IMAGE: "DOCUMENT_CHANGE_TITLE_IMAGE",
	DOCUMENT_CHANGE_FORM_VALUE: "DOCUMENT_CHANGE_FORM_VALUE",
	DOCUMENT_FORM_CHOICE_ADD: "DOCUMENT_FORM_CHOICE_ADD",
	DOCUMENT_FORM_CHOICE_REMOVE: "DOCUMENT_FORM_CHOICE_REMOVE",
	DOCUMENT_FORM_CHOICE_CLEAN: "DOCUMENT_FORM_CHOICE_CLEAN",
	DOCUMENT_FORM_CHOICE_CHANGE_TEXT: "DOCUMENT_FORM_CHOICE_CHANGE_TEXT",
	DOCUMENT_FORM_CHOICE_CHANGE_FILE: "DOCUMENT_FORM_CHOICE_CHANGE_FILE",
}

export default actions;
